/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.frame;
import application.model.*;
import data.validation.*;
import desktop.*;

import application.model.DBTableModel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author mattm
 */
public class AddAppointmentFrame extends javax.swing.JInternalFrame {

    DocumentFilter idFilter = new IDNumberFilter();
    /**
     * Creates new form AddAppointment
     */
    public AddAppointmentFrame() {
        initComponents();
        
        ((AbstractDocument)txtCustId.getDocument()).setDocumentFilter(idFilter);
        ((AbstractDocument)txtGrmId.getDocument()).setDocumentFilter(idFilter);
        ((AbstractDocument)txtPetId.getDocument()).setDocumentFilter(idFilter);
        
        tblCustPet.setVisible(false);
    }
    
    public AddAppointmentFrame(String id, char type){
        initComponents();
        tblCustPet.setVisible(false);
        
        if(type == 'c'){
            txtCustId.setText(id);
            DBTableModel.viewPets(tblCustPet, ModifyCSRecord.getId());
            tblCustPet.setVisible(true);
        } else {
            txtGrmId.setText(id);
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCustId = new javax.swing.JLabel();
        lblGrmId = new javax.swing.JLabel();
        lblPetId = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        lblNotes = new javax.swing.JLabel();
        txtGrmId = new javax.swing.JTextField();
        txtCustId = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        txtPetId = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustPet = new javax.swing.JTable();
        pnlSearch = new javax.swing.JPanel();
        lblField1 = new javax.swing.JLabel();
        cmbFieldGrm = new javax.swing.JComboBox<>();
        btnSearchGrm = new javax.swing.JButton();
        txtFieldGrm = new javax.swing.JTextField();
        btnClearGrm = new javax.swing.JButton();
        dateAppt = new org.jdesktop.swingx.JXDatePicker();
        btnRefreshCustPet = new javax.swing.JButton();
        pnlSearch1 = new javax.swing.JPanel();
        lblField2 = new javax.swing.JLabel();
        cmbFieldCust = new javax.swing.JComboBox<>();
        btnSearchCust = new javax.swing.JButton();
        txtFieldCust = new javax.swing.JTextField();
        btnClearCust = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        cmbTime = new javax.swing.JComboBox<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Appointment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 18))); // NOI18N

        lblCustId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblCustId.setText("Customer ID:");

        lblGrmId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblGrmId.setText("Groomer ID:");

        lblPetId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblPetId.setText("Pet ID:");

        txtNotes.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtNotes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNotes.setNextFocusableComponent(btnSubmit);

        lblNotes.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblNotes.setText("Notes:");

        txtGrmId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtGrmId.setNextFocusableComponent(txtPetId);

        txtCustId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtCustId.setNextFocusableComponent(txtGrmId);

        btnClose.setBackground(new java.awt.Color(255, 102, 102));
        btnClose.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.setNextFocusableComponent(dateAppt);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(51, 51, 255));
        btnSubmit.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setNextFocusableComponent(btnClose);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtPetId.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtPetId.setNextFocusableComponent(txtNotes);

        lblDate.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblDate.setText("Date:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer's Pets", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 14))); // NOI18N

        tblCustPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCustPet);

        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Groomers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 14))); // NOI18N

        lblField1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblField1.setText("Field 1:");

        cmbFieldGrm.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        cmbFieldGrm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Email", "Last Name", "ID Number", "ZIP" }));

        btnSearchGrm.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnSearchGrm.setText("Search");
        btnSearchGrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGrmActionPerformed(evt);
            }
        });

        txtFieldGrm.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        btnClearGrm.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnClearGrm.setText("Clear");
        btnClearGrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearGrmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addComponent(lblField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFieldGrm, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldGrm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSearchLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnClearGrm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchGrm)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField1)
                    .addComponent(cmbFieldGrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldGrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchGrm)
                    .addComponent(btnClearGrm)))
        );

        dateAppt.setFocusCycleRoot(true);
        dateAppt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        dateAppt.setNextFocusableComponent(cmbTime);

        btnRefreshCustPet.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnRefreshCustPet.setText("Refresh Customer's Pets");
        btnRefreshCustPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshCustPetActionPerformed(evt);
            }
        });

        pnlSearch1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Customers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 14))); // NOI18N

        lblField2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblField2.setText("Field 1:");

        cmbFieldCust.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        cmbFieldCust.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Email", "Last Name", "ID Number", "ZIP" }));

        btnSearchCust.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnSearchCust.setText("Search");
        btnSearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustActionPerformed(evt);
            }
        });

        txtFieldCust.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N

        btnClearCust.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnClearCust.setText("Clear");
        btnClearCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCustActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSearch1Layout = new javax.swing.GroupLayout(pnlSearch1);
        pnlSearch1.setLayout(pnlSearch1Layout);
        pnlSearch1Layout.setHorizontalGroup(
            pnlSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearch1Layout.createSequentialGroup()
                        .addComponent(lblField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbFieldCust, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldCust, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSearch1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnClearCust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchCust)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSearch1Layout.setVerticalGroup(
            pnlSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearch1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField2)
                    .addComponent(cmbFieldCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchCust)
                    .addComponent(btnClearCust)))
        );

        lblTime.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblTime.setText("Time:");

        cmbTime.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "8:00 AM", "11:00 AM", "3:00 PM" }));
        cmbTime.setNextFocusableComponent(txtCustId);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblGrmId)
                                                .addComponent(lblCustId)
                                                .addComponent(lblPetId))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtGrmId, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(txtCustId)
                                                .addComponent(txtPetId)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblDate)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                            .addComponent(dateAppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTime)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNotes))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(btnSubmit))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClose)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefreshCustPet))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnRefreshCustPet)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(dateAppt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustId)
                            .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrmId)
                            .addComponent(txtGrmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPetId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNotes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnClose))
                    .addComponent(pnlSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchGrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGrmActionPerformed
        String fieldOne = null,
        sType = "Groomer";
        int sField = cmbFieldGrm.getSelectedIndex();

        if(cmbFieldGrm.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "     Please select a field type.",
                "Search Field Check", JOptionPane.OK_OPTION);
        } else if (txtFieldGrm.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "     Please enter a field value.",
                "Search Field Check", JOptionPane.OK_OPTION);
        } else {
            CSSearchFrame sFrame = new CSSearchFrame(sType, sField, this.txtFieldGrm.getText());
            FetchApplication.addInternalFrame(this.getDesktopPane(), sFrame);
            sFrame.setVisible(true);
            sFrame.moveToFront();
        }
    }//GEN-LAST:event_btnSearchGrmActionPerformed

    private void btnClearGrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearGrmActionPerformed
        cmbFieldGrm.setSelectedIndex(0);
        txtFieldGrm.setText("");
    }//GEN-LAST:event_btnClearGrmActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        AppointmentModel tempAppt = null;
        
        String apptTime = (String) cmbTime.getSelectedItem();
        
        int custId = Integer.parseInt(txtCustId.getText()),
                grmId = Integer.parseInt(txtGrmId.getText()),
                petId = Integer.parseInt(txtPetId.getText()),
                splitIndex = apptTime.indexOf(" ");
      
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = dateAppt.getDate();
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        
        
        if ("".equals(txtCustId.getText())){
            JOptionPane.showMessageDialog(null, "Unable to Add New Appointment", "No Customer ID", JOptionPane.OK_OPTION);
        } else if ("".equals(txtGrmId.getText())){
            JOptionPane.showMessageDialog(null, "Unable to Add New Appointment", "No Groomer ID", JOptionPane.OK_OPTION);
        } else if ("".equals(txtPetId.getText())){
            JOptionPane.showMessageDialog(null, "Unable to Add New Appointment", "No Pet ID", JOptionPane.OK_OPTION);
        } else if (splitIndex == -1) {
            JOptionPane.showMessageDialog(null, "Unable to Add New Appointment", "No Time Selected", JOptionPane.OK_OPTION);
        } else {
            apptTime = apptTime.substring(0, splitIndex);
            
            try {
                tempAppt = new AppointmentModel(custId, grmId, petId, sqlDate, txtNotes.getText(), apptTime);
            } catch (ParseException ex) {
                Logger.getLogger(AddAppointmentFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        AppointmentModel.addAppointment(tempAppt);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustActionPerformed
        String fieldOne = null,
        sType = "Customer";
        int sField = cmbFieldCust.getSelectedIndex();

        if(cmbFieldCust.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "     Please select a field type.",
                "Search Field Check", JOptionPane.OK_OPTION);
        } else if (txtFieldCust.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "     Please enter a field value.",
                "Search Field Check", JOptionPane.OK_OPTION);
        } else {
            CSSearchFrame sFrame = new CSSearchFrame(sType, sField, this.txtFieldCust.getText());
            FetchApplication.addInternalFrame(this.getDesktopPane(), sFrame);
            sFrame.setVisible(true);
            sFrame.moveToFront();
        }
    }//GEN-LAST:event_btnSearchCustActionPerformed

    private void btnClearCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustActionPerformed
        cmbFieldCust.setSelectedIndex(0);
        txtFieldCust.setText("");
    }//GEN-LAST:event_btnClearCustActionPerformed

    private void btnRefreshCustPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshCustPetActionPerformed
        DBTableModel.viewPets(tblCustPet, Integer.parseInt(txtCustId.getText()));
        tblCustPet.setVisible(true);
    }//GEN-LAST:event_btnRefreshCustPetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCust;
    private javax.swing.JButton btnClearGrm;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefreshCustPet;
    private javax.swing.JButton btnSearchCust;
    private javax.swing.JButton btnSearchGrm;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbFieldCust;
    private javax.swing.JComboBox<String> cmbFieldGrm;
    private javax.swing.JComboBox<String> cmbTime;
    private org.jdesktop.swingx.JXDatePicker dateAppt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblField1;
    private javax.swing.JLabel lblField2;
    private javax.swing.JLabel lblGrmId;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPetId;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlSearch1;
    private javax.swing.JTable tblCustPet;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtFieldCust;
    private javax.swing.JTextField txtFieldGrm;
    private javax.swing.JTextField txtGrmId;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtPetId;
    // End of variables declaration//GEN-END:variables
}
