/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.frame;

import application.model.PetModel;
import data.validation.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author mattm
 */
public class AddPetFrame extends javax.swing.JInternalFrame {

    DocumentFilter nameFilter = new NameFilter();
    /**
     * Creates new form AddPetFrame
     */
    public AddPetFrame() {
        initComponents();
        
        ((AbstractDocument)txtPetName.getDocument()).setDocumentFilter(nameFilter);
        ((AbstractDocument)txtBreed.getDocument()).setDocumentFilter(nameFilter);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int) tk.getScreenSize().getWidth();
            int ysize = (int) tk.getScreenSize().getHeight();
            
        Dimension frameSize = this.getSize();
            
        this.setLocation((xsize - frameSize.width)/2, (ysize - frameSize.height)/2);
        this.setVisible(true);
    }
    
    public AddPetFrame(String focusID) {
        initComponents();
        
        ((AbstractDocument)txtPetName.getDocument()).setDocumentFilter(nameFilter);
        ((AbstractDocument)txtBreed.getDocument()).setDocumentFilter(nameFilter);
        
        this.setOwnerID(focusID);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int) tk.getScreenSize().getWidth();
            int ysize = (int) tk.getScreenSize().getHeight();
            
        Dimension frameSize = this.getSize();
            
        this.setLocation((xsize - frameSize.width)/2, (ysize - frameSize.height)/2);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSex = new javax.swing.ButtonGroup();
        btngPetType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblPetName = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        lblPetType = new javax.swing.JLabel();
        lblPetSex = new javax.swing.JLabel();
        lblBreed = new javax.swing.JLabel();
        txtBreed = new javax.swing.JTextField();
        lblOwnerID = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        rbtDog = new javax.swing.JRadioButton();
        rbtCat = new javax.swing.JRadioButton();
        lblOwnerIDValue = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add New Pet");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/internal/frame/dog_bowl.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Pet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 18))); // NOI18N
        jPanel1.setFocusTraversalPolicyProvider(true);

        lblPetName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblPetName.setText("Pet Name:");

        txtPetName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtPetName.setFocusCycleRoot(true);
        txtPetName.setNextFocusableComponent(rbtDog);

        lblPetType.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblPetType.setText("Pet Type:");

        lblPetSex.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblPetSex.setText("Sex:");

        lblBreed.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblBreed.setText("Breed:");

        txtBreed.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtBreed.setNextFocusableComponent(btnSubmit);

        lblOwnerID.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblOwnerID.setText("Owner ID:");

        btnSubmit.setBackground(new java.awt.Color(51, 51, 255));
        btnSubmit.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setNextFocusableComponent(btnReset);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setNextFocusableComponent(btnClose);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 102, 102));
        btnClose.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.setNextFocusableComponent(txtPetName);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btngSex.add(rbtMale);
        rbtMale.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rbtMale.setSelected(true);
        rbtMale.setText("Male");
        rbtMale.setNextFocusableComponent(rbtFemale);

        btngSex.add(rbtFemale);
        rbtFemale.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rbtFemale.setText("Female");
        rbtFemale.setNextFocusableComponent(txtBreed);

        btngPetType.add(rbtDog);
        rbtDog.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rbtDog.setSelected(true);
        rbtDog.setText("Dog");
        rbtDog.setNextFocusableComponent(rbtCat);

        btngPetType.add(rbtCat);
        rbtCat.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        rbtCat.setText("Cat");
        rbtCat.setNextFocusableComponent(rbtMale);

        lblOwnerIDValue.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblOwnerIDValue.setText("Invalid");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPetType)
                            .addComponent(lblPetName)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPetSex, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBreed, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtDog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtCat)))
                        .addGap(34, 34, 34)
                        .addComponent(lblOwnerID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOwnerIDValue, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBreed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPetName)
                    .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOwnerID)
                    .addComponent(lblOwnerIDValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPetType)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtDog)
                            .addComponent(rbtCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtMale)
                            .addComponent(rbtFemale)
                            .addComponent(lblPetSex)
                            .addComponent(btnReset)
                            .addComponent(btnSubmit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBreed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBreed)
                            .addComponent(btnClose))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String selectedType = this.getSelectedButtonText(btngPetType),
                selectedSex = this.getSelectedButtonText(btngSex);
        
        char petSex = selectedSex.charAt(0);
         
        if (txtPetName.getDocument().getLength() < 1) {
            JOptionPane.showMessageDialog(null, "Unable to Add New Pet", "No Name Entered", JOptionPane.OK_OPTION);
        } else if (txtBreed.getDocument().getLength() < 1) {
            JOptionPane.showMessageDialog(null, "Unable to Add New Pet", "No Breed Entered", JOptionPane.OK_OPTION);
        } else {
            
            String petName = "",
                    breed = "";
            try {
                petName = txtPetName.getDocument().getText(0, txtPetName.getDocument().getLength());
                breed = txtBreed.getDocument().getText(0, txtBreed.getDocument().getLength());
            } catch (BadLocationException ex) {
                Logger.getLogger(AddPetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            PetModel tempPet = new PetModel(petName, selectedType, petSex,
                breed, Integer.parseInt(lblOwnerIDValue.getText()));


            PetModel.addPet(tempPet);
            
            try {
                txtPetName.getDocument().remove(0, txtPetName.getDocument().getLength());
                txtBreed.getDocument().remove(0, txtBreed.getDocument().getLength());
            } catch (BadLocationException ex) {
                Logger.getLogger(AddPetFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnSubmitActionPerformed
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            txtPetName.getDocument().remove(0, txtPetName.getDocument().getLength());
            txtBreed.getDocument().remove(0, txtBreed.getDocument().getLength());
        } catch (BadLocationException ex) {
            Logger.getLogger(AddPetFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
            
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    public void setOwnerID(String focusID){
        lblOwnerIDValue.setText(focusID);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btngPetType;
    private javax.swing.ButtonGroup btngSex;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBreed;
    private javax.swing.JLabel lblOwnerID;
    private javax.swing.JLabel lblOwnerIDValue;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPetSex;
    private javax.swing.JLabel lblPetType;
    private javax.swing.JRadioButton rbtCat;
    private javax.swing.JRadioButton rbtDog;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtPetName;
    // End of variables declaration//GEN-END:variables
}
