/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal.frame;
import internal.frame.*;
import application.model.*;
import desktop.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mattm
 */
public class ModifyCSRecord extends javax.swing.JInternalFrame {
    private static char type = 'n';
    private static int id = -1;
    
    public static char getType(){ return ModifyCSRecord.type; }
    public static void setType(char focusType){ ModifyCSRecord.type = focusType; }
    
    public static int getId() { return ModifyCSRecord.id; }
    public static void setId(int idNum) { ModifyCSRecord.id = idNum; }
    
    
    /**
     * Creates new form ModifyCSRecord
     */
    public ModifyCSRecord() {
        initComponents();
        tblViewAppts.setVisible(false);
    }
    
    public ModifyCSRecord(CustomerModel cust){
        initComponents();
        tblViewAppts.setVisible(false);
        
        int custID = cust.getCustomerId();
        StringBuilder sb = new StringBuilder(cust.getPhone())
                                .insert(3,"-")
                                .insert(7,"-");
        String phoneNum = sb.toString();
        
        
        txtFirstName.setText(cust.getFirstName());
        txtMInitial.setText(cust.getMiddleInitial());
        txtLastName.setText(cust.getLastName());
        txtAddress1.setText(cust.getAddressLine1());
        txtAddress2.setText(cust.getAddressLine2());
        txtCity.setText(cust.getCity());
        txtState.setText(cust.getState());
        txtZIP.setText(cust.getZip());
        txtEmail.setText(cust.getEmail());
        //txtPassword.setText(cust.getPass());
        txtPhone.setText(phoneNum);
        
        
        lblFocusIDValue.setText(Integer.toString(custID));
        lblFocusID.setText("Customer ID:");
        
        ModifyCSRecord.setType('c');
        ModifyCSRecord.setId(custID);
    }
    
    public ModifyCSRecord(GroomerModel grm){
        initComponents();
        tblViewAppts.setVisible(false);
        
        int grmID = grm.getGroomerId();
        
        StringBuilder sb = new StringBuilder(grm.getPhone())
                                .insert(3,"-")
                                .insert(7,"-");
        String phoneNum = sb.toString();
        
        txtFirstName.setText(grm.getFirstName());
        txtMInitial.setText(grm.getMiddleInitial());
        txtLastName.setText(grm.getLastName());
        txtAddress1.setText(grm.getAddressLine1());
        txtAddress2.setText(grm.getAddressLine2());
        txtCity.setText(grm.getCity());
        txtState.setText(grm.getState());
        txtZIP.setText(grm.getZip());
        txtEmail.setText(grm.getEmail());
        //txtPassword.setText(cust.getPass());
        txtPhone.setText(phoneNum);
        
        
        lblFocusIDValue.setText(Integer.toString(grmID));
        lblFocusID.setText("Groomer ID:");
        
        ModifyCSRecord.setType('g');
        ModifyCSRecord.setId(grmID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblMInital = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        lblFocusID = new javax.swing.JLabel();
        lblFocusIDValue = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JLabel();
        txtMInitial = new javax.swing.JLabel();
        txtLastName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtAddress1 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JLabel();
        txtState = new javax.swing.JLabel();
        txtZIP = new javax.swing.JLabel();
        btnViewAppts = new javax.swing.JButton();
        btnModAppt = new javax.swing.JButton();
        btnAddAppt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAppts = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Modify Record");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selected Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 18))); // NOI18N
        jPanel1.setFocusTraversalPolicyProvider(true);

        lblFirstName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblFirstName.setText("First Name:");

        lblMInital.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblMInital.setText("Middle Initial:");

        lblLastName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblLastName.setText("Last Name:");

        lblPhone.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblPhone.setText("Phone:");

        lblEmail.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblEmail.setText("Email:");

        lblAddress1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblAddress1.setText("Address:");

        lblCity.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblState.setText("State:");

        lblZip.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblZip.setText("ZIP:");

        btnClose.setBackground(new java.awt.Color(255, 102, 102));
        btnClose.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.setNextFocusableComponent(btnAddAppt);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblFocusID.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lblFocusID.setText("ID Number:");

        lblFocusIDValue.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        lblFocusIDValue.setText("******");

        txtFirstName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtFirstName.setText("*");

        txtMInitial.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtMInitial.setText("*");

        txtLastName.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtLastName.setText("*");

        txtPhone.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtPhone.setText("*");

        txtEmail.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtEmail.setText("*");

        txtAddress1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtAddress1.setText("*");

        txtAddress2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtAddress2.setText("*");

        txtCity.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtCity.setText("*");

        txtState.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtState.setText("**");

        txtZIP.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        txtZIP.setText("*****");

        btnViewAppts.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnViewAppts.setText("View Appointments");
        btnViewAppts.setNextFocusableComponent(btnClose);
        btnViewAppts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewApptsActionPerformed(evt);
            }
        });

        btnModAppt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnModAppt.setText("Modify Appointment");
        btnModAppt.setNextFocusableComponent(btnViewAppts);
        btnModAppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModApptActionPerformed(evt);
            }
        });

        btnAddAppt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnAddAppt.setText("Add Appointment");
        btnAddAppt.setFocusCycleRoot(true);
        btnAddAppt.setNextFocusableComponent(btnModAppt);
        btnAddAppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddApptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                                    .addComponent(txtMInitial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 98, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblFirstName)
                                                .addComponent(lblMInital)
                                                .addComponent(lblLastName))
                                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress1)
                                    .addComponent(lblState)
                                    .addComponent(lblCity)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblZip)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblFocusID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblFocusIDValue))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtState)
                                        .addComponent(txtZIP)
                                        .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(11, 11, 11)))
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnModAppt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddAppt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewAppts)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFocusIDValue)
                    .addComponent(lblFocusID))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1)
                    .addComponent(txtFirstName)
                    .addComponent(txtAddress1)
                    .addComponent(lblFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMInital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(lblState)
                            .addComponent(txtPhone)
                            .addComponent(txtState)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMInitial)
                            .addComponent(txtAddress2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCity)
                            .addComponent(lblCity))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZip)
                        .addComponent(txtZIP)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAppts)
                    .addComponent(btnAddAppt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnModAppt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Appointments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 18))); // NOI18N

        tblViewAppts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViewAppts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnViewApptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewApptsActionPerformed
        DBTableModel.viewAppts(tblViewAppts, ModifyCSRecord.getId(), ModifyCSRecord.getType());
        tblViewAppts.setVisible(true);
    }//GEN-LAST:event_btnViewApptsActionPerformed

    private void btnAddApptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddApptActionPerformed
        AddAppointmentFrame addAppt = new AddAppointmentFrame(lblFocusIDValue.getText(), ModifyCSRecord.getType());
        FetchApplication.addInternalFrame(this.getDesktopPane(), addAppt);
        addAppt.setVisible(true);
        addAppt.moveToFront();
    }//GEN-LAST:event_btnAddApptActionPerformed

    private void btnModApptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModApptActionPerformed
        AppointmentModel appt = new AppointmentModel();
        
        String apptModId =  JOptionPane.showInputDialog(null,"Please enter an appointment ID Number: ");
        //AppointmentModel.deleteAppt(Integer.parseInt(apptDeleteId));
        
        appt = AppointmentModel.setFocus(Integer.parseInt(apptModId));
        
        if(appt.getApptId() == -1){
            JOptionPane.showMessageDialog(null, "     Appointment not found.", 
               "Appointment ID Validation", JOptionPane.OK_OPTION);
        } else {
            ModifyAppointmentFrame modApptFrame = new ModifyAppointmentFrame(appt);
            FetchApplication.addInternalFrame(this.getDesktopPane(), modApptFrame);
            modApptFrame.setVisible(true);
            modApptFrame.moveToFront();
        }
    }//GEN-LAST:event_btnModApptActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAppt;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnModAppt;
    private javax.swing.JButton btnViewAppts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFocusID;
    private javax.swing.JLabel lblFocusIDValue;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMInital;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTable tblViewAppts;
    private javax.swing.JLabel txtAddress1;
    private javax.swing.JLabel txtAddress2;
    private javax.swing.JLabel txtCity;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFirstName;
    private javax.swing.JLabel txtLastName;
    private javax.swing.JLabel txtMInitial;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtState;
    private javax.swing.JLabel txtZIP;
    // End of variables declaration//GEN-END:variables
}
